server:
  port: 9000

spring:
  application:
    name: cloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848 #Nacos作为配置中心地址
        file-extension: yaml #指定yaml格式的配置
        group: HUANGSHI_GROUP
        namespace:
    sentinel:
      transport:
        dashboard: localhost:8080
        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
        port: 8719

#激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true