server:
  port: 9000

eureka:
  instance:
    hostname: localhost # 主机名
    prefer-ip-address: true # 是否将自己的ip注册到eureka中，默认false 注册 主机名
    ip-address: 127.0.0.1 # 设置当前实例ip,自己配置的
    instance-id: 狗熊:${eureka.instance.ip-address}:${spring.application.name}:${server.port} # 设置web控制台显示的 实例id
    lease-renewal-interval-in-seconds: 3 # 每一次eureka client 向 eureka server发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 9 # 如果9秒内eureka server没有收到eureka client的心跳包，则剔除该服务
  client:
    register-with-eureka: true #一启动是否将自己的路径 注册到eureka上
    fetch-registry: true #一启动是否需要从eureka中抓取数据
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka-server1:8761/eureka,http://eureka-server2:8761/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信
spring:
  application:
    name: eureka-consumer # 设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径
# 设置Ribbon的超时时间
ribbon:
  ConnectTimeout: 1000 # 连接超时时间 默认1s
  ReadTimeout: 3000 # 逻辑处理的超时时间 默认1s

# 设置当前的日志级别 debug，feign只支持记录debug级别的日志
logging:
  level:
    com.qxy: debug

# 开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true
