server:
  port: 8762
spring:
  application:
    name: eureka-server2222
# eureka 配置
# eureka 一共有4部分 配置
# 1. dashboard:eureka的web控制台配置
# 2. server:eureka的服务端配置
# 3. client:eureka的客户端配置
# 4. instance:eureka的实例配置

eureka:
  instance:
    hostname: eureka-server2 # 主机名
  server:
    enable-self-preservation: true #是否开启自我保护机制，默认true
    eviction-interval-timer-in-ms: 120000  #清理间隔（单位毫秒，默认是60*1000）
  client:
    register-with-eureka: false # 是否将自己的路径 注册到eureka上。eureka server 不需要的，eureka provider client 需要
    fetch-registry: false # 是否需要从eureka中抓取路径。eureka server 不需要的，eureka consumer client 需要
    service-url:
      defaultZone: http://eureka-server1:8671/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信
